server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api.php {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/html/api.php;
        fastcgi_param SCRIPT_NAME /api.php;
        fastcgi_pass backend:9000;
    }
}